language: python
python:
  - '2.7'
git:
  depth: 3
install:
  - pip install --upgrade --upgrade-strategy eager pip setuptools wheel
  - pip install --upgrade --upgrade-strategy eager -e .[dev]
jobs:
  include:
    - stage: test
      script: py.test -vv -c /dev/null --cov=productionsystem --cov-report=term --cov-report=html --cov-fail-under=0 tests
    - stage: style
      script: py.test -vv -c tests/style_check.cfg --pylint --pylint-error-types=EF --pep8 --pep257 productionsystem
stages:
  - test
  - style
