language: python
python:
  - '2.7'
git:
  depth: 3
install:
  - pip install --upgrade --upgrade-strategy eager pip setuptools wheel
  - pip install --upgrade --upgrade-strategy eager -e .[dev]
jobs:
  include:
    - stage: test
      script: py.test -c tests/unit_tests.cfg
    - stage: style
      script: py.test -c tests/style_check.cfg
stages:
  - test
  - style
